# Generated by Django 3.2.5 on 2022-11-04 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('others', '0002_item'),
        ('finance', '0002_invoice_invoiceitem_invoicesubject_receipt'),
        ('corecode', '0004_auto_20201124_0614'),
        ('subjects', '0002_subject_subjectbulkupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='others.item'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicsession'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.academicterm'),
        ),
    ]
