# Generated by Django 3.2.5 on 2022-11-05 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_subject_subjectbulkupload'),
        ('others', '0002_item'),
        ('work', '0002_work'),
        ('finance', '0004_invoice_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='item',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='others.item'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subject',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='work',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='work.work'),
        ),
    ]
