# Generated by Django 3.2.5 on 2022-11-05 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0004_auto_20201124_0614'),
        ('finance', '0007_auto_20221105_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='balance_from_previous_term',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='class_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corecode.tag'),
        ),
    ]
