# Generated by Django 3.2.5 on 2022-11-05 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_auto_20221105_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['subject', 'work', 'item', 'due_date']},
        ),
    ]
