# Generated by Django 3.2.5 on 2022-11-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0012_auto_20221106_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicesubject',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='invoicework',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='InvoiceItems',
        ),
    ]
