# Generated by Django 3.2.5 on 2022-11-06 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20221106_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
