# Generated by Django 3.2.5 on 2022-11-06 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_invoiceitem_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='amount',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
