# Generated by Django 3.2.5 on 2022-11-03 07:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('corecode', '0007_alter_tag_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.CharField(choices=[('!', '较低'), ('!!', '一般'), ('!!!', '较高')], default='!', max_length=15)),
                ('item', models.CharField(max_length=200)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('period', models.TextField(blank=True)),
                ('tag', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='corecode.tag')),
            ],
            options={
                'ordering': ['item', 'priority', 'tag'],
            },
        ),
    ]
