# Generated by Django 3.2.5 on 2022-11-03 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_alter_tag_options'),
        ('others', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corecode.tag'),
        ),
    ]
