# Generated by Django 3.2.5 on 2022-11-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_alter_item_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
