# Generated by Django 3.2.5 on 2022-11-03 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_alter_item_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='period',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
