# Generated by Django 3.2.5 on 2022-11-03 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0006_alter_item_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item', 'priority', 'tag']},
        ),
    ]
