# Generated by Django 3.0.5 on 2020-05-06 14:20

from django.db import migrations
from django.contrib.auth.models import User


def default_site_config(apps, schema_editor):
    """Default site configurations"""

    User.objects.create_superuser("box", "admin@schoolapp.com", "python2022")

    Config = apps.get_model("corecode", "SiteConfig")
    Config.objects.bulk_create(
        [
            Config(key="school_name", value="HUST"),
            Config(key="school_slogan", value="在华科的每一步，每一步都算数。"),
            Config(key="school_address", value="1037号森林"),
        ]
    )

    Session = apps.get_model("corecode", "AcademicSession")
    Session.objects.bulk_create(
        [
            Session(name="2022/2023", current=True),
        ]
    )

    Term = apps.get_model("corecode", "AcademicTerm")
    Term.objects.bulk_create(
        [
            Term(name="1st Term", current=True),
            Term(name="2nd Term", current=False),
        ]
    )

    Course = apps.get_model("corecode", "Course")
    Course.objects.bulk_create(
        [
            Course(name="Mathematics"),
            Course(name="English"),
        ]
    )

    Tag = apps.get_model("corecode", "Tag")
    Tag.objects.bulk_create(
        [
            Tag(name="Life"),
            Tag(name="Hobby"),
        ]
    )


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(default_site_config),
    ]
