# Generated by Django 3.2.5 on 2022-11-03 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0005_otherclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Class', 'verbose_name_plural': 'Classes'},
        ),
    ]
