# Generated by Django 3.2.5 on 2022-11-03 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corecode', '0006_alter_tag_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
    ]
