# Generated by Django 3.2.5 on 2022-11-04 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('credit', models.CharField(max_length=200, unique=True)),
                ('subject', models.CharField(max_length=200)),
                ('professor', models.CharField(max_length=200)),
                ('online_source', models.URLField()),
                ('property', models.CharField(choices=[('compulsory', '必修'), ('optional', '选修')], default='必修', max_length=10)),
                ('date_of_test', models.DateField(default=django.utils.timezone.now)),
                ('others', models.TextField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='subjects/pictures/')),
            ],
            options={
                'ordering': ['subject', 'professor', 'online_source'],
            },
        ),
        migrations.CreateModel(
            name='SubjectBulkUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('csv_file', models.FileField(upload_to='subjects/bulkupload/')),
            ],
        ),
    ]
