# Generated by Django 3.2.5 on 2022-10-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='credit',
            new_name='学分',
        ),
    ]
