# Generated by Django 3.2.5 on 2022-10-08 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_rename_credit_subject_学分'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['课程', '授课老师', 'online_source']},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='firstname',
            new_name='授课老师',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='current_status',
            new_name='状态',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='surname',
            new_name='课程',
        ),
    ]
