# Generated by Django 3.2.5 on 2022-10-08 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_auto_20221008_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='property',
            field=models.CharField(choices=[('必修', 'compulsory'), ('选修', 'optional')], default='必修', max_length=10),
        ),
    ]
