# Generated by Django 3.2.5 on 2022-10-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0005_alter_subject_property'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['subject', 'professor', 'online_source']},
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='学分',
            new_name='credit',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='授课老师',
            new_name='professor',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='状态',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='课程',
            new_name='subject',
        ),
        migrations.AlterField(
            model_name='subject',
            name='property',
            field=models.CharField(choices=[('compulsory', 'Compulsory'), ('optional', 'Optional')], default='compulsory', max_length=10),
        ),
    ]
