# Generated by Django 3.2.5 on 2022-10-08 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0006_auto_20221008_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='property',
            field=models.CharField(choices=[('compulsory', '必修'), ('optional', '选修')], default='必修', max_length=10),
        ),
    ]
