# Generated by Django 3.2.5 on 2022-10-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0007_alter_subject_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='online_source',
            field=models.URLField(),
        ),
    ]
