# Generated by Django 3.2.5 on 2022-10-17 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0009_rename_date_of_birth_subject_data_of_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='data_of_test',
            new_name='date_of_test',
        ),
    ]
