# Generated by Django 3.2.5 on 2022-10-17 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0011_auto_20221017_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='address',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='current_class',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='date_of_admission',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='parent_mobile_number',
        ),
    ]
