# Generated by Django 3.0.5 on 2020-05-06 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "current_method",
                    models.CharField(
                        choices=[("private", "个人"), ("collaboration", "协作")],
                        default="private",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("firstname", models.CharField(max_length=200)),
                ("other_name", models.CharField(blank=True, max_length=200)),
                (
                    "priority",
                    models.CharField(
                        choices=[("!", "较低"), ("!!", "一般"), ("!!!", "较高")],
                        default="!",
                        max_length=15,
                    ),
                ),
                ("date_of_birth", models.DateField(default=django.utils.timezone.now)),
                (
                    "date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
                ("address", models.TextField(blank=True)),
                ("others", models.TextField(blank=True)),
            ],
        ),
    ]
