# Generated by Django 3.2.5 on 2022-11-03 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
    ]
