# Generated by Django 3.0.8 on 2020-11-24 12:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("work", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="work",
            name="note",
            field=models.CharField(
                blank=True,
                max_length=200,
            ),
        ),
    ]
