# Generated by Django 3.2.5 on 2022-11-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_auto_20201124_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='current_method',
            field=models.CharField(choices=[('private', '个人'), ('collaboration', '协作')], default='private', max_length=15),
        ),
    ]
