# Generated by Django 3.2.5 on 2022-11-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0003_alter_work_current_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='address',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='work',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='work',
            name='other_name',
        ),
        migrations.RemoveField(
            model_name='work',
            name='others',
        ),
        migrations.AlterField(
            model_name='work',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
