# Generated by Django 3.2.5 on 2022-11-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_auto_20221103_0040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='date',
        ),
        migrations.AddField(
            model_name='work',
            name='period',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
